name: Set Creation Date on Project Items

on:
  project_v2:
    types: [item_added]

jobs:
  set-creation-date:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      projects: write
    
    steps:
      - name: Set Creation Date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ github.event.project_v2.id }}
          ITEM_ID: ${{ github.event.project_v2_item.id }}
        run: |
          # Get current date in YYYY-MM-DD format
          TODAY=$(date +%Y-%m-%d)
          
          # Get project details to find the Creation Date field ID
          PROJECT_FIELDS=$(gh api graphql -f query='
            query($projectId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2IterationField {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f projectId=$PROJECT_ID)
          
          # Extract the Creation Date field ID
          CREATION_DATE_FIELD_ID=$(echo $PROJECT_FIELDS | jq -r '.data.node.fields.nodes[] | select(.name == "Creation date") | .id')
          
          if [ "$CREATION_DATE_FIELD_ID" = "null" ] || [ -z "$CREATION_DATE_FIELD_ID" ]; then
            echo "Creation Date field not found in project"
            exit 1
          fi
          
          # Update the Creation Date field for the item
          gh api graphql -f query='
            mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Date!) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $projectId
                itemId: $itemId
                fieldId: $fieldId
                value: {
                  date: $value
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f projectId=$PROJECT_ID -f itemId=$ITEM_ID -f fieldId=$CREATION_DATE_FIELD_ID -f value=$TODAY
          
          echo "Set Creation Date to $TODAY for item $ITEM_ID"
